/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingWebCompanionRouteImport } from './routes/_marketing/web-companion'
import { Route as MarketingSupportRouteImport } from './routes/_marketing/support'
import { Route as MarketingRaycastRouteImport } from './routes/_marketing/raycast'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingPocketAlternativeRouteImport } from './routes/_marketing/pocket-alternative'
import { Route as MarketingIosAppRouteImport } from './routes/_marketing/ios-app'
import { Route as MarketingDocsRouteImport } from './routes/_marketing/docs'
import { Route as MarketingChromeExtensionRouteImport } from './routes/_marketing/chrome-extension'
import { Route as MarketingArticlesRouteImport } from './routes/_marketing/articles'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as MarketingArticlesSaveLinksWithRaycastRouteImport } from './routes/_marketing/articles_.save-links-with-raycast'
import { Route as MarketingArticlesReadLaterAppChromeIphoneRouteImport } from './routes/_marketing/articles_.read-later-app-chrome-iphone'
import { Route as MarketingArticlesReadLaterApiRouteImport } from './routes/_marketing/articles_.read-later-api'
import { Route as AppLibraryFoldersFolderIdRouteImport } from './routes/_app/library_.folders.$folderId'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingWebCompanionRoute = MarketingWebCompanionRouteImport.update({
  id: '/web-companion',
  path: '/web-companion',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSupportRoute = MarketingSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingRaycastRoute = MarketingRaycastRouteImport.update({
  id: '/raycast',
  path: '/raycast',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPocketAlternativeRoute =
  MarketingPocketAlternativeRouteImport.update({
    id: '/pocket-alternative',
    path: '/pocket-alternative',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingIosAppRoute = MarketingIosAppRouteImport.update({
  id: '/ios-app',
  path: '/ios-app',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDocsRoute = MarketingDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingChromeExtensionRoute =
  MarketingChromeExtensionRouteImport.update({
    id: '/chrome-extension',
    path: '/chrome-extension',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesRoute = MarketingArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => MarketingRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const MarketingArticlesSaveLinksWithRaycastRoute =
  MarketingArticlesSaveLinksWithRaycastRouteImport.update({
    id: '/articles_/save-links-with-raycast',
    path: '/articles/save-links-with-raycast',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesReadLaterAppChromeIphoneRoute =
  MarketingArticlesReadLaterAppChromeIphoneRouteImport.update({
    id: '/articles_/read-later-app-chrome-iphone',
    path: '/articles/read-later-app-chrome-iphone',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesReadLaterApiRoute =
  MarketingArticlesReadLaterApiRouteImport.update({
    id: '/articles_/read-later-api',
    path: '/articles/read-later-api',
    getParentRoute: () => MarketingRoute,
  } as any)
const AppLibraryFoldersFolderIdRoute =
  AppLibraryFoldersFolderIdRouteImport.update({
    id: '/library_/folders/$folderId',
    path: '/library/folders/$folderId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof MarketingIndexRoute
  '/connect': typeof AppConnectRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRoute
  '/articles': typeof MarketingArticlesRoute
  '/chrome-extension': typeof MarketingChromeExtensionRoute
  '/docs': typeof MarketingDocsRoute
  '/ios-app': typeof MarketingIosAppRoute
  '/pocket-alternative': typeof MarketingPocketAlternativeRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/raycast': typeof MarketingRaycastRoute
  '/support': typeof MarketingSupportRoute
  '/web-companion': typeof MarketingWebCompanionRoute
  '/articles/read-later-api': typeof MarketingArticlesReadLaterApiRoute
  '/articles/read-later-app-chrome-iphone': typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  '/articles/save-links-with-raycast': typeof MarketingArticlesSaveLinksWithRaycastRoute
  '/library/folders/$folderId': typeof AppLibraryFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof MarketingIndexRoute
  '/connect': typeof AppConnectRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRoute
  '/articles': typeof MarketingArticlesRoute
  '/chrome-extension': typeof MarketingChromeExtensionRoute
  '/docs': typeof MarketingDocsRoute
  '/ios-app': typeof MarketingIosAppRoute
  '/pocket-alternative': typeof MarketingPocketAlternativeRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/raycast': typeof MarketingRaycastRoute
  '/support': typeof MarketingSupportRoute
  '/web-companion': typeof MarketingWebCompanionRoute
  '/articles/read-later-api': typeof MarketingArticlesReadLaterApiRoute
  '/articles/read-later-app-chrome-iphone': typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  '/articles/save-links-with-raycast': typeof MarketingArticlesSaveLinksWithRaycastRoute
  '/library/folders/$folderId': typeof AppLibraryFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/connect': typeof AppConnectRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_marketing/articles': typeof MarketingArticlesRoute
  '/_marketing/chrome-extension': typeof MarketingChromeExtensionRoute
  '/_marketing/docs': typeof MarketingDocsRoute
  '/_marketing/ios-app': typeof MarketingIosAppRoute
  '/_marketing/pocket-alternative': typeof MarketingPocketAlternativeRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/raycast': typeof MarketingRaycastRoute
  '/_marketing/support': typeof MarketingSupportRoute
  '/_marketing/web-companion': typeof MarketingWebCompanionRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/articles_/read-later-api': typeof MarketingArticlesReadLaterApiRoute
  '/_marketing/articles_/read-later-app-chrome-iphone': typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  '/_marketing/articles_/save-links-with-raycast': typeof MarketingArticlesSaveLinksWithRaycastRoute
  '/_app/library_/folders/$folderId': typeof AppLibraryFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/connect'
    | '/inbox'
    | '/library'
    | '/settings'
    | '/articles'
    | '/chrome-extension'
    | '/docs'
    | '/ios-app'
    | '/pocket-alternative'
    | '/privacy'
    | '/raycast'
    | '/support'
    | '/web-companion'
    | '/articles/read-later-api'
    | '/articles/read-later-app-chrome-iphone'
    | '/articles/save-links-with-raycast'
    | '/library/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/connect'
    | '/inbox'
    | '/library'
    | '/settings'
    | '/articles'
    | '/chrome-extension'
    | '/docs'
    | '/ios-app'
    | '/pocket-alternative'
    | '/privacy'
    | '/raycast'
    | '/support'
    | '/web-companion'
    | '/articles/read-later-api'
    | '/articles/read-later-app-chrome-iphone'
    | '/articles/save-links-with-raycast'
    | '/library/folders/$folderId'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_marketing'
    | '/_app/connect'
    | '/_app/inbox'
    | '/_app/library'
    | '/_app/settings'
    | '/_marketing/articles'
    | '/_marketing/chrome-extension'
    | '/_marketing/docs'
    | '/_marketing/ios-app'
    | '/_marketing/pocket-alternative'
    | '/_marketing/privacy'
    | '/_marketing/raycast'
    | '/_marketing/support'
    | '/_marketing/web-companion'
    | '/_marketing/'
    | '/_marketing/articles_/read-later-api'
    | '/_marketing/articles_/read-later-app-chrome-iphone'
    | '/_marketing/articles_/save-links-with-raycast'
    | '/_app/library_/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/web-companion': {
      id: '/_marketing/web-companion'
      path: '/web-companion'
      fullPath: '/web-companion'
      preLoaderRoute: typeof MarketingWebCompanionRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/support': {
      id: '/_marketing/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MarketingSupportRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/raycast': {
      id: '/_marketing/raycast'
      path: '/raycast'
      fullPath: '/raycast'
      preLoaderRoute: typeof MarketingRaycastRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pocket-alternative': {
      id: '/_marketing/pocket-alternative'
      path: '/pocket-alternative'
      fullPath: '/pocket-alternative'
      preLoaderRoute: typeof MarketingPocketAlternativeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/ios-app': {
      id: '/_marketing/ios-app'
      path: '/ios-app'
      fullPath: '/ios-app'
      preLoaderRoute: typeof MarketingIosAppRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/docs': {
      id: '/_marketing/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof MarketingDocsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/chrome-extension': {
      id: '/_marketing/chrome-extension'
      path: '/chrome-extension'
      fullPath: '/chrome-extension'
      preLoaderRoute: typeof MarketingChromeExtensionRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles': {
      id: '/_marketing/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof MarketingArticlesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/articles_/save-links-with-raycast': {
      id: '/_marketing/articles_/save-links-with-raycast'
      path: '/articles/save-links-with-raycast'
      fullPath: '/articles/save-links-with-raycast'
      preLoaderRoute: typeof MarketingArticlesSaveLinksWithRaycastRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/read-later-app-chrome-iphone': {
      id: '/_marketing/articles_/read-later-app-chrome-iphone'
      path: '/articles/read-later-app-chrome-iphone'
      fullPath: '/articles/read-later-app-chrome-iphone'
      preLoaderRoute: typeof MarketingArticlesReadLaterAppChromeIphoneRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/read-later-api': {
      id: '/_marketing/articles_/read-later-api'
      path: '/articles/read-later-api'
      fullPath: '/articles/read-later-api'
      preLoaderRoute: typeof MarketingArticlesReadLaterApiRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/library_/folders/$folderId': {
      id: '/_app/library_/folders/$folderId'
      path: '/library/folders/$folderId'
      fullPath: '/library/folders/$folderId'
      preLoaderRoute: typeof AppLibraryFoldersFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppLibraryFoldersFolderIdRoute: typeof AppLibraryFoldersFolderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppInboxRoute: AppInboxRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppLibraryFoldersFolderIdRoute: AppLibraryFoldersFolderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MarketingRouteChildren {
  MarketingArticlesRoute: typeof MarketingArticlesRoute
  MarketingChromeExtensionRoute: typeof MarketingChromeExtensionRoute
  MarketingDocsRoute: typeof MarketingDocsRoute
  MarketingIosAppRoute: typeof MarketingIosAppRoute
  MarketingPocketAlternativeRoute: typeof MarketingPocketAlternativeRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingRaycastRoute: typeof MarketingRaycastRoute
  MarketingSupportRoute: typeof MarketingSupportRoute
  MarketingWebCompanionRoute: typeof MarketingWebCompanionRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingArticlesReadLaterApiRoute: typeof MarketingArticlesReadLaterApiRoute
  MarketingArticlesReadLaterAppChromeIphoneRoute: typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  MarketingArticlesSaveLinksWithRaycastRoute: typeof MarketingArticlesSaveLinksWithRaycastRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingArticlesRoute: MarketingArticlesRoute,
  MarketingChromeExtensionRoute: MarketingChromeExtensionRoute,
  MarketingDocsRoute: MarketingDocsRoute,
  MarketingIosAppRoute: MarketingIosAppRoute,
  MarketingPocketAlternativeRoute: MarketingPocketAlternativeRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingRaycastRoute: MarketingRaycastRoute,
  MarketingSupportRoute: MarketingSupportRoute,
  MarketingWebCompanionRoute: MarketingWebCompanionRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingArticlesReadLaterApiRoute: MarketingArticlesReadLaterApiRoute,
  MarketingArticlesReadLaterAppChromeIphoneRoute:
    MarketingArticlesReadLaterAppChromeIphoneRoute,
  MarketingArticlesSaveLinksWithRaycastRoute:
    MarketingArticlesSaveLinksWithRaycastRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
